version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: ielts_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: ielts_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd!
      ME_CONFIG_MONGODB_URL: mongodb://admin:P%40ssw0rd!@mongodb:27017/
    depends_on:
      - mongodb

  postgres:
    image: postgres:16
    container_name: ielts_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "110521"
      POSTGRES_DB: IeltsAuth
    ports:
      - "5433:5432"   # host 5433 -> tránh đụng PostgreSQL cài native trên Windows (5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ielts_pgadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ielts.local
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd!
    depends_on:
      - postgres

volumes:
  mongodb_data:
  postgres_data:
